# Form implementation generated from reading ui file 'Currency.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from idlelib.colorizer import color_config

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("central widget")
        self.CurrencyTitle = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CurrencyTitle.setGeometry(QtCore.QRect(80, 20, 321, 51))
        self.CurrencyTitle.setObjectName("CurrencyTitle")
        self.CurrencyTitle.setStyleSheet("color: purple; font-weight: bold;")
        self.AmountLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.AmountLabel.setGeometry(QtCore.QRect(100, 90, 101, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.AmountLabel.setFont(font)
        self.AmountLabel.setAcceptDrops(False)
        self.AmountLabel.setObjectName("AmountLabel")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 100, 151, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.FromLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.FromLabel.setGeometry(QtCore.QRect(90, 200, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.FromLabel.setFont(font)
        self.FromLabel.setAcceptDrops(False)
        self.FromLabel.setObjectName("FromLabel")
        self.ToLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ToLabel.setGeometry(QtCore.QRect(340, 200, 111, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ToLabel.setFont(font)
        self.ToLabel.setAcceptDrops(False)
        self.ToLabel.setObjectName("ToLabel")
        self.FromBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.FromBox.setGeometry(QtCore.QRect(70, 260, 111, 41))
        self.FromBox.setObjectName("FromBox")
        self.FromBox.addItem("Choose")
        self.FromBox.addItem("USD")
        self.FromBox.addItem("INR")
        self.FromBox.addItem("EUR")
        self.ToBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.ToBox.setGeometry(QtCore.QRect(310, 260, 111, 41))
        self.ToBox.setObjectName("ToBox")
        self.ToBox.addItem("Choose")
        self.ToBox.addItem("USD")
        self.ToBox.addItem("INR")
        self.ToBox.addItem("EUR")
        self.ResultsDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.ResultsDisplay.setGeometry(QtCore.QRect(60, 490, 380, 60))
        self.ResultsDisplay.setObjectName("ResultsDisplay")
        self.ResultsDisplay.setStyleSheet("color: green; font-weight: bold;")
        self.ResultsDisplay.setFont(QtGui.QFont("Arial", 16))
        self.ResultsDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.ConvertButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ConvertButton.setGeometry(QtCore.QRect(190, 340, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ConvertButton.setFont(font)
        self.ConvertButton.setObjectName("ConvertButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuCurrency_Convert = QtWidgets.QMenu(parent=self.menubar)
        self.menuCurrency_Convert.setObjectName("menuCurrency_Convert")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCurrency_Convert.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Currency Converter"))
        self.CurrencyTitle.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.6pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Currency Converter</span></p></body></html>"))


        self.AmountLabel.setText(_translate("MainWindow", "Amount:"))
        self.AmountLabel.setStyleSheet("color: purple;")

        self.FromLabel.setText(_translate("MainWindow", "FROM:"))
        self.FromLabel.setStyleSheet("color: purple;")

        self.ToLabel.setText(_translate("MainWindow", "TO:"))
        self.ToLabel.setStyleSheet("color: purple;")

        self.ConvertButton.setText(_translate("MainWindow", "CONVERT"))
        self.ConvertButton.setStyleSheet("color: white")
        self.menuCurrency_Convert.setTitle(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
